export const BASE_URL = 'https://norma.nomoreparties.space/api/';

export const SET_ALL_INGREDIENTS: 'SET_ALL_INGREDIENTS' = 'SET_ALL_INGREDIENTS';

export const ADD_BURGER_INGREDIENT: 'ADD_BURGER_INGREDIENT' = 'ADD_BURGER_INGREDIENT';
export const DELETE_BURGER_INGREDIENT: 'DELETE_BURGER_INGREDIENT' = 'DELETE_BURGER_INGREDIENT';
export const UPDATE_BURGER_INGREDIENTS_ORDER: 'UPDATE_BURGER_INGREDIENTS_ORDER' = 'UPDATE_BURGER_INGREDIENTS_ORDER';
export const CHANGE_ORDER: 'CHANGE_ORDER' = 'CHANGE_ORDER';

export const CREATE_ORDER: 'CREATE_ORDER' = 'CREATE_ORDER';
export const CLEAR_ORDER: 'CLEAR_ORDER' = 'CLEAR_ORDER';
export const CLEAR_BURGER_CONSTRUCTOR: 'CLEAR_BURGER_CONSTRUCTOR' = 'CLEAR_BURGER_CONSTRUCTOR';

export const SET_USER: 'SET_USER' = 'SET_USER';
export const SET_IS_AUTH_CHECKED: 'SET_IS_AUTH_CHECKED' = 'SET_IS_AUTH_CHECKED';